## CIND830 - Python Programming for Data Science  
### Assignment 1 (10% of the final grade) 
### Due on July 11, 2022 11:59 PM 

*****
This is a Jupyter Notebook document that extends a simple formatting syntax for authoring HTML and PDF. Review [this](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html) website for more details on using Jupyter Notebooks.

Consider using a Jupyter Notebook platform to complete this assignment. Ensure using **Python 3.7 release or higher** then complete the assignment by inserting your Python code wherever seeing the string `#INSERT YOUR ANSWER HERE.`

When you click the `File` button, from the top navigation bar, then select `Export Notebook to HTML`, an HTML document will be generated that includes both the assignment content and the output of any embedded Python code chunks.

Use [these](https://www.ryerson.ca/courses/students/tutorials/assignments/) guidelines to submit **both** the IPYNB and the exported file (HTML). Failing to submit both files will be subject to mark deduction.

Please be advised that you cannot get more than 100% in this assignment, and the **BONUS** question (if there is any) will only be graded if all other questions have been submitted.

*****


### **Question 1  [25 pts]**:

According to the Toronto Real Estate Trends and the Housing Market Report for June 2022 (published in https://www.zolo.ca/toronto-real-estate/trends) in June 2022, the average house price in GTA decreased to $1,187,564 in June 2022 with a month-to-month change rate of -4.7 percent. As of June 2022, Toronto housing data shows median days on market for a home is 14 days.

```
regionName = "Greater Toronto Area"
juneAvePrice = 1187564
changeRate = -0.047
daysInMarket = 14
decreasing = True
```

**a) [5 pts]**  Use the built-in `print()` function to display the literal and type of the five variables listed above.

In [1]:
regionName = "Greater Toronto Area"
juneAvePrice = 1187564
changeRate = -0.047
daysInMarket = 14
decreasing = True

#Variable Literals
print(regionName)
print(juneAvePrice)
print(changeRate)
print(daysInMarket)
print(decreasing)

#Variable Types
print(type(regionName))
print(type(juneAvePrice))
print(type(changeRate))
print(type(daysInMarket))
print(type(decreasing))

Greater Toronto Area
1187564
-0.047
14
True
<class 'str'>
<class 'int'>
<class 'float'>
<class 'int'>
<class 'bool'>


**b) [5 pts]**  Suppose that the decrease rate stays the same in July 2022. Compute and display the new expected Average Selling Price for this month, and round up the result to the nearest whole number.

In [2]:
changePrice = juneAvePrice*changeRate
julyAvePrice = juneAvePrice+changePrice
print(round(julyAvePrice))

1131748


**c) [5 pts]**  Compute and display the difference between the Average Selling Price in June 2022 and that in July 2022.

In [3]:
avgSellingPriceDiff = juneAvePrice - julyAvePrice
print(avgSellingPriceDiff)

55815.507999999914


**d) [5 pts]**  Convert the variable `junAvePrice` to a floating-point number
then display the new literal and type.

In [4]:
juneAvePrice = float(juneAvePrice)
print(juneAvePrice)
print(type(juneAvePrice))

1187564.0
<class 'float'>


**e) [5 pts]**  Given that `var1` is the `julyAvePrice` variable rounded up to the nearest whole number,
and `var2` is the `changeRate` variable rounded to two decimal places.

Print the following statement:
The average selling price might be `var1` in July 2022, which is a `var2` month-to-month change rate.

In [5]:
var1 = round(julyAvePrice)
var2 = round(changeRate,2)
print("The average selling price might be",var1,"in July 2022, which is a",var2,"month-to-month change rate.")

The average selling price might be 1131748 in July 2022, which is a -0.05 month-to-month change rate.


*****


### Question 2  **[35 pts]**:

**a) [15 pts]**  Write a Python program that accepts a list of marks then prints the letter grade and description according to the [Grading System](https://continuing.ryerson.ca/contentManagement.do?method=load&code=CM000034) of the Chang School of Continuing Education.

For example, if the user enters `90, 120, -12, 71.5, 62.5`, the output would be as follows:

| Mark | Letter Grade | Performance Description |
|:-:|:-:|:-:|
| 90 | A+ | Excellent |
| 120 | Not Possible | Not Possible |
| -12 | Not Possible | Not Possible |
| 71.5 | B- | Good |
| 62.5 | C | Satisfactory |

In [6]:
marks = list(map(float,input("Enter the marks ").split(',')))
print("\n")

print("Mark\tLetter Grade\tPerformance Description")

for stdmarks in marks:
  print(stdmarks,end="\t")
  if 79 < stdmarks <= 100:
    if 89 < stdmarks <= 100:
      print("A+",end="\t\t")
    elif 84 < stdmarks <= 89:
      print("A",end="\t\t")
    elif 79 < stdmarks <= 84:
      print("A-",end="\t\t")
    print("Excellent")
  elif 69 < stdmarks <= 79:
    if 76 < stdmarks <= 79:
      print("B+",end="\t\t")
    elif 72 < stdmarks <= 76:
      print("B",end="\t\t")
    elif 69 < stdmarks <= 72:
      print("B-",end="\t\t")
    print("Good")
  elif 59 < stdmarks <= 69:
    if 66 < stdmarks <= 69:
      print("C+",end="\t\t")
    elif 62 < stdmarks <= 66:
      print("C",end="\t\t")
    elif 59 < stdmarks <= 62:
      print("C-",end="\t\t")
    print("Satisfactory")
  elif 49 < stdmarks <= 59:
    if 56 < stdmarks <= 59:
      print("D+",end="\t\t")
    elif 52 < stdmarks <= 56:
      print("D",end="\t\t")
    elif 49 < stdmarks <= 52:
      print("D-",end="\t\t")
    print("Marginal")
  elif 0 <= stdmarks <= 49:
    print("F\t\tUnsatisfactory")
  else:
    print("Not Possible\tNot Possible")

Enter the marks 90, 120, -12, 71.5, 62.5


Mark	Letter Grade	Performance Description
90.0	A+		Excellent
120.0	Not Possible	Not Possible
-12.0	Not Possible	Not Possible
71.5	B-		Good
62.5	C		Satisfactory


**b)**  **[10 pts]** Write a code to compute and print the sum of squares of only the `Excellent` marks.

For example, if the user enters `90.5, 120, -12, 71.3, 82.2, 62.5`, then the output should be: <br>
`The Excellent marks are:  90.5, 82.2`<br>
`The sum of squares is  14947.09`

In [7]:
marks = list(map(float,input("Enter the marks ").split(',')))

squareSums = 0

exmarks=[]
for stdmarks in marks:
  if 79<stdmarks<=100 :
    exmarks.append(stdmarks)
    squareSums += stdmarks **2

print("The Excellent marks are:", ', '.join(map(str,exmarks)))
print("The sum of squares is",squareSums)

Enter the marks 90.5, 120, -12, 71.3, 82.2, 62.5
The Excellent marks are: 90.5, 82.2
The sum of squares is 14947.09


**c)**  **[10 pts]** Write a code to compute and print the `Median`, `Average` and `Variance` of the marks between 0 and 100, inclusively, after rounding each mark to the nearest integer.

For example, if the user enters `59.8, 60, 29.5, 30, 50, 200`, then the output should be: <br>
`The valid marks are:  60, 60, 30, 30, 50 `<br>
`Median is 50 ; Average is 46 ; Variance is 230`

Hint: Use the [statistics](https://docs.python.org/3.8/library/statistics.html) module as it provides functions to calculate mathematical statistics of numeric data.

In [8]:
import statistics
marks = list(map(float,input("Enter the marks ").split(',')))

rmarks=[]
for stdmarks in marks:
  if 0<=stdmarks<=100:
    rmarks.append(round(stdmarks))

print("The valid marks are:", ', '.join(map(str, rmarks)))

print("Median is", statistics.median(rmarks), "; Average is", statistics.mean(rmarks), "; Variance is", statistics.variance(rmarks))

Enter the marks 59.8, 60, 29.5, 30, 50, 200
The valid marks are: 60, 60, 30, 30, 50
Median is 50 ; Average is 46 ; Variance is 230


****

### Question 3  **[40 pts]**:
Write a program that accepts the lengths of three sides of a triangle as inputs then prints the type and compute the properties of the triangle according to the listed conditions and mathematical formulae.

**a)**  **[20 pts]** Ensure that all side lengths are positive and the sum of any two side lengths is greater than the third side length.

In [9]:
length1 = float(input("Enter the Length of the First Side "))
length2 = float(input("Enter the Length of the Second Side "))
length3 = float(input("Enter the Length of the Third Side "))

if length1<1 or length2<1 or length3<1:
  print("Please enter Positive Lengths")
  raise SystemExit
else:
  print("All Side Lengths are Positive")  

if length1+length2>length3 and length2+length3>length1 and length3+length1>length2:
  print("Sum of Lengths of any two sides is greater than the third side length. Triangle is valid & exists.")
else:
  print("Sum of Lengths of any two sides is not greater than the third side length. Triangle does not exists.\nPlease enter Valid Triangle Side Lengths")
  raise SystemExit

Enter the Length of the First Side 4
Enter the Length of the Second Side 5
Enter the Length of the Third Side 6
All Side Lengths are Positive
Sum of Lengths of any two sides is greater than the third side length. Triangle is valid & exists.


**b)**  **[20 pts]** Display the type of the triangle according to the following restrictions:

Equilateral Triangle: If the triangle has three congruent sides.

Isosceles Triangle: If the triangle has two equal sides.
 
Scalene Triangle: If the triangle has no congruent sides, and each side have a different length.
 
Right Triangle: If the square of one side equals the sum of the squares of the other
two sides.

In [10]:
length1 = float(input("Enter the Length of the First Side "))
length2 = float(input("Enter the Length of the Second Side "))
length3 = float(input("Enter the Length of the Third Side "))

if length1<1 or length2<1 or length3<1:
  print("Please enter Positive Lengths")
  raise SystemExit 

if not(length1+length2>length3 and length2+length3>length1 and length3+length1>length2):
  print("Sum of Lengths of any two sides is not greater than the third side length. Triangle does not exists.\nPlease enter Valid Triangle Side Lengths")
  raise SystemExit

if length1 == length2 == length3:
  print("It is an Equilateral Triangle")
elif length1 == length2 or length2 == length3 or length3 == length1:
  print("It is an Isosceles Triangle")
  if length1**2==length2**2+length3**2 or length2**2==length3**2+length1**2 or length3**2==length1**2+length2**2:
    print("It is also a Right Triangle")
elif length1 != length2 != length3:
  print("It is a Scalene Triangle")
  if length1**2==length2**2+length3**2 or length2**2==length3**2+length1**2 or length3**2==length1**2+length2**2:
    print("It is also a Right Triangle")


Enter the Length of the First Side 4
Enter the Length of the Second Side 5
Enter the Length of the Third Side 6
It is a Scalene Triangle


#### This is the end of assignment 1